### ISSUE TITLE
How does it compare to Vault

### ISSUE THREAD

**Issue by PunKeel** [pinterest/knox#1]
Hello,

No offense, but as a user I would really love to know how your software compares to [Vault](https://github.com/hashicorp/vault).

I won't answer for you, but I might have some clues ... for instance: _seamless integration in Go apps_.

PS/ I'm sorry this is your first issue. Thanks a lot for open sourcing this!

**Comment by devinlundberg** [comment]
I have some of the differences that I am aware of here: https://github.com/pinterest/knox/wiki/Similar-Solutions

In regards to seamless integration with Go, Vault is also written in Go, but (as far as I know) they don't provide a function or interface that takes care of using Vault from your code. The client and the rotation process are also pretty different.

One thing to note is that I've never actually used Vault in production. I've mostly just read over the docs, briefly looked over the source, and talked to a few people who are using it. So if you or anyone you know is more familiar and notices an error, omission, or misunderstanding in that wiki page, feel free to let me know and we can fix it.

**Comment by PunKeel** [comment]
@devinlundberg Thanks, I hadn't seen that page!

Looks like Vault has a client library: https://github.com/hashicorp/vault/tree/d3f1176e035f89f22184062d4fb565df10b3a6c3/api
(So does Knox)

**Comment by devinlundberg** [comment]
You are totally right. Thanks for the link!
