### ISSUE TITLE
List ACLs

### ISSUE THREAD

**Issue by 0x0ece** [pinterest/knox#16]
Add a client command to list all ACLs related to a key.

TODO:
- command name: `acls`?
- output format, e.g.: `<provider> <type><accessType>` (same letters as in `access`)
    ```
    $ knox acls myservice:mykey
    0x0ece Ua
    security-team Ga
    ```
- do we want to apply any filter, e.g. based on user permissions? I don't think so because anything the client receives it should be able to print...

**Comment by 0x0ece** [comment]
Preliminary code, for ref:
https://github.com/0x0ece/knox/commit/4c6a7f3dcbccc3ee28846deb69cdafc97d081083

**Comment by devinlundberg** [comment]
Lets just leave it as `knox acl` for now.

The json format is probably the easiest to implement and also involves the least work.

A filter could be interesting. like given a machine with name xxxx does it have access to key yyy, but this probably isn't necessary for the first iteration.
