### ISSUE TITLE
Knox dynamic secrets generation 

### ISSUE THREAD

**Issue by RohanKurane** [pinterest/knox#24]
I am trying to research Knox to see if it would be a good idea to use to store secrets. I had a few questions-
1. Does Knox support dynamic secrets generation i.e does it generate new secrets on the fly for the client ? 
2. Or is it a static key store and keys need to be supplied thru a file or a string to store in Knox DB ?
3. Is MySql the only supported backed storage for the knox keys ? 
4. If the keys are stored in the DB, where is the key to the DB stored ? A HSM i assume. 

I would really appreciate answers since i will surely have more questions soon. 

Appreciate the help!

**Comment by krockpot** [comment]
> Does Knox support dynamic secrets generation i.e does it generate new secrets on the fly for the client ?
> Or is it a static key store and keys need to be supplied thru a file or a string to store in Knox DB ?

As you suspected, Knox is a static keystore and keys are updated / managed through the cli. You can perform dynamic key rotation by giving some system write access to a key and periodically updating the key with new data. For example: `knox access -w -M key_id_to_rotate machine_performing_rotation` and updating the key with something like `tail /dev/urandom | knox add key_id_to_rotate`.

> Is MySql the only supported backed storage for the knox keys?

Yes, although other storage methods could be added.

> If the keys are stored in the DB, where is the key to the DB stored ? A HSM i assume.

The DB is encrypted with an AES_GCM key. As far as where that key is stored, that's entirely up to you. An HSM would be a good option, although you could also use something like AWS KMS. Here's a link to the threat model, which might help clarify these ideas: https://github.com/pinterest/knox/wiki/Security-Model.

**Comment by RohanKurane** [comment]
Thanks @krockpot !
What is the method to add a custom storage backend to store the Knox keys ? Is it documented anywhere ?

**Comment by krockpot** [comment]
If you want a custom storage backend, you would want to implement the DB interface found at https://github.com/pinterest/knox/blob/master/server/keydb/keydb.go#L49. That's more or less just implementing the CRUD operations for whatever storage backend you choose.

**Comment by RohanKurane** [comment]
Thanks @krockpot !
Pardon my ignorance, but it seems that all Knox does is - 

User inputs 'encryption key' to add to Knox DB
Knox DB encrypts the key before storing in DB
User can get/add/update/remove keys from/to the Knox DB. 

There appears to be access control in place as well. 

Am I missing anything with regards to functionality ?

**Comment by krockpot** [comment]
Yes, the primary functionality is storing encrypted secrets and providing an interface for performing versioning and access control.

**Comment by RohanKurane** [comment]
Thanks for confirming @krockpot 
Would you be open to connect on LinkedIn ?

**Comment by devinlundberg** [comment]
I think all the questions have been resolved here. Please reopen if I missed something.
