### ISSUE TITLE
Knox client doesn't support Windows

### ISSUE THREAD

**Issue by klauern** [pinterest/knox#3]
I don't believe the dev_client works with Windows:

```
C:> go install github.com/pinterest/knox/cmd/dev_client
# github.com/pinterest/knox/client
..\golang\src\github.com\pinterest\knox\client\daemon.go:285: undefined: syscall.Flock
..\golang\src\github.com\pinterest\knox\client\daemon.go:285: undefined: syscall.LOCK_EX
..\golang\src\github.com\pinterest\knox\client\daemon.go:285: undefined: syscall.LOCK_NB
..\golang\src\github.com\pinterest\knox\client\daemon.go:295: undefined: syscall.Flock
..\golang\src\github.com\pinterest\knox\client\daemon.go:295: undefined: syscall.LOCK_EX
..\golang\src\github.com\pinterest\knox\client\daemon.go:295: undefined: syscall.LOCK_NB
..\golang\src\github.com\pinterest\knox\client\daemon.go:309: undefined: syscall.Flock
..\golang\src\github.com\pinterest\knox\client\daemon.go:309: undefined: syscall.LOCK_UN
..\golang\src\github.com\pinterest\knox\client\daemon.go:309: undefined: syscall.LOCK_NB
..\golang\src\github.com\pinterest\knox\client\daemon.go:319: undefined: syscall.Flock
..\golang\src\github.com\pinterest\knox\client\daemon.go:319: too many errors
```

**Comment by devinlundberg** [comment]
The KeysFile struct (https://github.com/pinterest/knox/blob/master/client/daemon.go#L268 ) depends on having a file lock syscall available and that isn't available on windows. 

The reason that this file lock call is there to begin with is that if multiple clients are registering or unregistering keys at the same time, the register file will get into a bad state. 

I don't have a windows machine to test on, but if I did, I think the correct solution would be to have two implementations of the KeysFile struct in two different files daemon_unix.go and daemon_windows.go. (most everything should be the same besides the Flock call) daemon_unix.go would contain the current implementations KeysFile, all its functions, and NewKeysFile. daemon_windows.go should contain some sort of way to ensure that only one client is writing at a time in the Lock and Unlock function.

**Comment by klauern** [comment]
I think boltdb does something similar: 

- https://github.com/boltdb/bolt/blob/master/bolt_windows.go
- https://github.com/boltdb/bolt/blob/master/bolt_unix.go

Although I'm not clear on advisory and exclusive locks, so I'm not sure how this would affect it.
