### ISSUE TITLE
is there option for HA?

### ISSUE THREAD

**Issue by yosefy** [pinterest/knox#33]
we need to work in multi DC environment. does knox support it?

thanks

**Comment by krockpot** [comment]
The main constraint would be the data.

https://github.com/pinterest/knox/blob/master/server/keydb/keydb.go implements a SQL DB for the backend. As long as your DB is accessible or cloned multi DC, Knox should work no problem and scale as much as you want. 

Keep in mind these keys are meant to be encrypted at rest, so whatever cryptor your use should be accessible in each of those DC.

More info: https://github.com/pinterest/knox/wiki/Knox-Backend-Database

**Comment by yosefy** [comment]
do you think mysql master-master replication will be a problem?

**Comment by krockpot** [comment]
probably not, depending on how write heavy your usage of knox is. If you're constantly writing, that replication would have to happen frequently and quickly to make sure your secondary has all the key information.
